enableGlobalCache: true

nodeLinker: pnp

npmAuthToken: "${NPM_DIFUKS_TOKEN:-}"

npmPublishAccess: public

npmRegistryServer: "https://registry.npmjs.com/"

packageExtensions:
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-typescript: 3.6.1
  ts-patch@*:
    peerDependencies:
      typescript: "*"

tsEnableAutoTypes: true

yarnPath: .yarn/releases/yarn-4.2.1.cjs
