nodeLinker: pnp

tsEnableAutoTypes: true

npmAuthToken: "${NPM_DIFUKS_TOKEN:-}"

npmPublishAccess: public

npmRegistryServer: "https://registry.npmjs.com/"

enableGlobalCache: true

packageExtensions:
  ts-patch@*:
    peerDependencies:
      typescript: "*"
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-typescript: 3.6.1

yarnPath: .yarn/releases/yarn-4.0.2.cjs
